# Site settings
title: 创客工坊
email: via313@gmail.com
description: "关注智能硬件,Arduino开发."
baseurl: ""
url: "http://viator42.github.io"
username: "viator42"
# Build settings
markdown: kramdown
permalink: pretty
