# Site settings
title: Viator42's Blog
email: viator42@qq.com
description: "这是我的个人博客,主要是对所学知识的梳理和总结,同时也希望能够帮到其他童鞋"
baseurl: ""
url: "http://viator42.github.io"
username: "viator42"
# Build settings
markdown: kramdown
permalink: pretty
favicon: "/static/images/favicon.png"
